[package]
name = "nth"
version = "0.1.0"
authors = ["Aliou Diallo <code@aliou.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
